version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - app-tier
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    container_name: backend
    build:
      context: ./MyTask
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQLDB_HOST=db
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-tier
